-- CREATE DATABASE gymbro;
-- Пользователи (users) → Тренировки (workouts) → Упражнения на тренировке (workout_exercises) → Подходы (sets)
--                      |
--                      v
--                  Упражнения (exercises)